### ISSUE TITLE
Bug: Wrong type for longitude/latitude for netbox_site

### ISSUE THREAD

**Issue by FragmentedPacket** [netbox-community/ansible_modules#416] opened 2021-01-14 14:17 UTC
##### ISSUE TYPE

 - Bug Report

##### SUMMARY

Type should be `str` instead of `float`

**Comment by Kralian** [comment] 2021-01-17 08:40
# Environment

    Python version: Any
    NetBox version: <=1.2.1

# Steps to Reproduce

Create netbox_site with geo location:

```
netbox.netbox.netbox_site:
  data:
    name: "testsite"
    latitude: 1.234
    longitude: 1.234
```

# Expected Behavior

On first update it should be added
On second update it should not have changed.

# Observed Behavior

On first update it gets update
On second update it gets marked as changed

If you create a site with longitude and latitude they will always show as changed because of str/float convertions even if they have the same value and aren't changed.

The right solution might be to fully implement floats, so that they're converted to floats in the json from the api, the easy way out is changingI think the easy solution is to drop floats and convert them to str.

```diff
--- plugins/modules/netbox_site.py.org  2021-01-17 09:36:17.561084152 +0100
+++ plugins/modules/netbox_site.py      2021-01-17 09:36:31.645350723 +0100
@@ -98,12 +98,12 @@
         description:
           - Latitude in decimal format
         required: false
-        type: float
+        type: str
       longitude:
         description:
           - Longitude in decimal format
         required: false
-        type: float
+        type: str
       contact_name:
         description:
           - Name of contact for site
@@ -253,8 +253,8 @@
                     description=dict(required=False, type="str"),
                     physical_address=dict(required=False, type="str"),
                     shipping_address=dict(required=False, type="str"),
-                    latitude=dict(required=False, type="float"),
-                    longitude=dict(required=False, type="float"),
+                    latitude=dict(required=False, type="str"),
+                    longitude=dict(required=False, type="str"),
                     contact_name=dict(required=False, type="str"),
                     contact_phone=dict(required=False, type="str"),
                     contact_email=dict(required=False, type="str"),
```

**Closed** 2021-01-17 23:03 UTC
Labels: PR Required, bug
