### ISSUE TITLE
Creating Site fails, "name missing but present"

### ISSUE THREAD

**Issue by pabe-github** [netbox-community/ansible_modules#531] opened 2021-05-28 13:36 UTC
##### ISSUE TYPE
 - Bug Report

###### Ansible:
ansible [core 2.11.0]

###### Netbox:
(v2.11.3)

###### Collection:
netbox.netbox:3.1.1

##### SUMMARY
Running a task to create a site fails with "msg": "state is present but all of the following are missing: name", but name is present:
fatal: [somehost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "asn": null,
                "comments": null,
                "contact_email": null,
                "contact_name": null,
                "contact_phone": null,
                "custom_fields": null,
                "description": null,
                "facility": null,
                "latitude": null,
                "longitude": null,
                **"name": "some-name",**
                "physical_address": null,
                "region": null,
                "shipping_address": null,
                "slug": null,
                "status": null,
                "tags": null,
                "tenant": "some-tenant",
                "time_zone": null
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "https://netbox.ourdomain.tld/",
            "query_params": null,
            "state": "present",
            "validate_certs": true
        }
    },
    **"msg": "state is present but all of the following are missing: name"**
}

##### STEPS TO REPRODUCE

```yaml
    - name: Create site
      delegate_to: localhost
      netbox.netbox.netbox_site:
        netbox_url: https://netbox.outdomain.tld/
        netbox_token: OURTOKEN
        state: present
        data:
          tenant: "some-tenant"
          name: "some-name"
```

##### EXPECTED RESULTS
Create the site in netbox

##### ACTUAL RESULTS
Fails before even trying to connect to our netbox instance

```

**Comment by pabe-github** [comment] 2021-05-28 13:42
Whups, duplicate: https://github.com/netbox-community/ansible_modules/issues/529
Sorry about that.
However, it still seems to be a problem as @andybro19 reports this problem still exists with 2.11.1
Could you link the issues and reopen 529?

**Comment by 2bithacker** [comment] 2021-05-28 15:30
Duplicate of #529

**Closed by 2bithacker** 2021-05-28 15:30 UTC
