### ISSUE TITLE
[Feature]: Add support for virtual disks to be on the netbox dyanmic inventory

### ISSUE THREAD

**Issue by damo2929** [netbox-community/ansible_modules#1164] opened 2024-02-01 14:08 UTC
### NetBox version

V3.7

### Feature type

Change to existing Module

### Proposed functionality

Add new section against inventory items that includes disks allocated using the new virtual disk interface.

### Use case

adding virtual disks to the dynamic inventory will allow ansible to loop over the inventory and ensure that the disks are present and with the correct sizes in the hypervisor.

**Comment by sc68cal** [comment] 2024-02-06 20:58
This appears to be a duplicate of #1141

**Closed** 2024-02-06 20:58 UTC
Labels: Enhancement
