### ISSUE TITLE
Please use #!/usr/bin/env python insead of #!/usr/bin/python as it fails to execute in virtual environments

### ISSUE THREAD

**Issue by mpsOxygen** [netbox-community/ansible_modules#290] opened 2020-07-28 11:26 UTC
##### ISSUE TYPE

 - Bug Report

###### Ansible:

ansible==2.9.11
###### Netbox:

pynetbox==5.0.5
###### Collection:

0.3.1
##### SUMMARY

Every module starts with #!/usr/bin/python preventing corect usage from inside a virtual env. The corect shebang is #!/usr/bin/env python.
##### STEPS TO REPRODUCE

Install the collections on a system, then create a virtual env an activate it. Install pynetbox with pip in that venv and try to run any module that makes use of it.

```yaml

```

##### EXPECTED RESULTS

The playbook should run and execute the module.
##### ACTUAL RESULTS

The playbook fails saying that pynetbox is not installed for /usr/bin/python

```

```

**Comment by FragmentedPacket** [comment] 2020-08-01 03:02
I'm kind of curious as to if you see this issue with the core Ansible modules as well? The shebang appears to be used with most, if not all, core Ansible modules.

I'm also using a virtualenv and these all work for me with no issue using the venv and nothing extra set.

What is the full output of a `-vvvv` run of a failing playbook for you?

**Comment by mpsOxygen** [comment] 2020-08-03 16:54
Well this is strange, I changed all the shebangs back to what they where and it still works. The other day it wouldn't work even after a reboot. If I manage to reproduce it I will let you know.

**Comment by ThomasADavis** [comment] 2020-08-03 21:33
I thought ansible actually removes/edits that first line, and when you run it with a '-vvvv', you'll see it not using that first line, but running it via the discovered python, which I've had problems with the in the past..

**Comment by cpmills1975** [comment] 2020-08-04 12:16
Presumably the shebang is only required when running the script directly from the command line. A python module imported in to another python module and run from there would, presumably, use the python interpreter that performed the import.

**Comment by FragmentedPacket** [comment] 2020-08-04 13:42
We've sometimes have had to set the `ANSIBLE_PYTHON_INTERPRETER` variable sometimes working with virtualenvs for it to work properly as well, but maybe the discovered python is working for me in my dev environment.

I'm going to close this issue, but please re-open if you have issues again and setting the python interpreter doesn't work for you and we can investigate further.

**Closed by FragmentedPacket** 2020-08-04 13:42 UTC
Labels: Discussion

**Comment by mpsOxygen** [comment] 2020-08-04 22:31
I hit the bug again, looks like it's a problem with ansible not using the python from within the venv. If I set it in ansible.cfg to the on in the venv it works. Weird.

**Comment by FragmentedPacket** [comment] 2020-08-04 23:26
That is intended behavior, but I do agree it is weird that it seems to be intermittent.
