### ISSUE TITLE
[Feature]: Module for IP address ranges

### ISSUE THREAD

**Issue by fabricat** [netbox-community/ansible_modules#740] opened 2022-02-21 16:32 UTC
### NetBox version

v3.1.7

### Feature type

New Module

### Proposed functionality

That would be great to manage IP ranges (introduced in Netbox 3.0, see #834) via Ansible.

### Use case

I am trying to automatically add DHCP reserved ranges into Netbox, in order to have a clear view over my private network.

**Comment by rodvand** [comment] 2022-02-21 16:55
Duplicate of https://github.com/netbox-community/ansible_modules/issues/628

**Comment by sc68cal** [comment] 2022-02-21 17:30
Closed as duplicate

**Closed by sc68cal** 2022-02-21 17:30 UTC
