### ISSUE TITLE
Can't assign existing IP to vm interface with netbox_ip_address

### ISSUE THREAD

**Issue by garbled1** [netbox-community/ansible_modules#315] opened 2020-08-23 17:00 UTC
##### ISSUE TYPE

 - Bug Report
###### Ansible:

ansible 2.9.1
  config file = None
  configured module search path = ['/home/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]

###### Netbox:

2.8.5
###### Collection:

1.0.0
##### SUMMARY

Can't assign IP to vm interface with netbox_ip_address
##### STEPS TO REPRODUCE

```yaml
- name: Assign IP to interface
  netbox.netbox.netbox_ip_address:
    netbox_url: '{{ netbox_server }}'
    netbox_token: '{{ netbox_token }}'
    data:
      prefix: '{{ netbox_prefix }}'
      #vrf: '{{ netbox_vrf }}'
      address: '{{ ansible_default_ipv4.address }}'
      dns_name: '{{ inventory_hostname_short }}'
      #family: 4
      interface:
        name: Ethernet
        virtual_machine: '{{ inventory_hostname_short }}'
    state: present
  register: vm_ip_info
  delegate_to: localhost

```

##### EXPECTED RESULTS

Attach existing IP address to the interface.  I have already defined the IP in netbox, but now I want it attached to this interface.

I've tried with and without the /23, multiple combinations.. nothing works.

##### ACTUAL RESULTS

```
{
    "msg": "address does not exist on existing object. Check to make sure valid field.",
    "changed": false,
    "invocation": {
        "module_args": {
            "netbox_url": "http://fafnir.garbled.net",
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "data": {
                "prefix": "192.168.10.0/23",
                "address": "192.168.10.32/23",
                "dns_name": "antares",
                "interface": {
                    "name": "Ethernet",
                    "virtual_machine": "antares"
                },
                "family": null,
                "vrf": null,
                "tenant": null,
                "status": null,
                "role": null,
                "description": null,
                "nat_inside": null,
                "tags": null,
                "custom_fields": null
            },
            "state": "present",
            "validate_certs": true,
            "query_params": null
        }
    },
    "_ansible_no_log": false,
    "_ansible_delegated_vars": {}
}
```

**Comment by ThomasADavis** [comment] 2020-08-24 16:46
Is the device really called 'Ethernet' you want to add an IP to?  Or is it like 'eth0'.

**Comment by garbled1** [comment] 2020-08-24 19:48
I did actually name it "Ethernet", I guess eth0 would be better, but, eh.

**Comment by FragmentedPacket** [comment] 2020-08-28 01:45
You shouldn't need the `prefix` specified here. I assume if you remove that, it should work.

If that does work, I believe we can fix this by adding `mutually_exclusive` to the module to prevent this issue.

**Comment by FragmentedPacket** [comment] 2020-08-28 01:52
I haven't been able to reproduce this :(

**Comment by FragmentedPacket** [comment] 2020-09-03 03:17
@garbled1 Any update on this? I would like to get this taken care of you, but haven't been able to reproduce.

**Comment by fdallaca** [comment] 2020-09-08 08:45
Hi @FragmentedPacket , I have the same issue using collections v1.0.2 on Ansible Tower 3.7.2:

**SOFTWARE VERSIONS**
ansible 2.9.11
python version = 3.6

Netbox:
715e1d13643e (v2.8.7)

Collection:
v1.0.2

**SUMMARY**
Can't create/assign IP to vm interface with netbox_ip_address (same error if the ip already exist).

**STEPS TO REPRODUCE**
```
# Create/Ensure all interface ip
- name: Create/Ensure all ip
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      address: "{{ item | ipaddr('address')}}"
      prefix: "{{ item | ipaddr('network/prefix')}}"
      interface:
        name: "interface_{{ interface_item.name }}"
        virtual_machine: "{{ ext_hostname }}"
  loop: "{{ iparray }}"
```

**ACTUAL RESULTS**
```
{
    "msg": "address does not exist on existing object. Check to make sure valid field.",
    "changed": false,
    "exception": "  File \"/tmp/ansible_netbox.netbox.netbox_ip_address_payload_15kqw_2n/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 885, in _update_netbox_object\n    if serialized_nb_obj[key] != updated_obj[key]:\n",
    "invocation": {
        "module_args": {
            "netbox_url": "***",
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "data": {
                "address": "10.100.8.66",
                "prefix": "10.100.8.0/23",
                "interface": {
                    "name": "interface_311_Server-Backend-3",
                    "virtual_machine": "ansibledeploy11.private.cineca.it"
                },
                "family": null,
                "vrf": null,
                "tenant": null,
                "status": null,
                "role": null,
                "description": null,
                "nat_inside": null,
                "dns_name": null,
                "tags": null,
                "custom_fields": null
            },
            "state": "present",
            "validate_certs": true,
            "query_params": null
        }
    },
    "_ansible_no_log": false,
    "item": "10.100.8.66/23",
    "ansible_loop_var": "item",
    "_ansible_item_label": "10.100.8.66/23"
}
```

**Comment by FragmentedPacket** [comment] 2020-09-08 12:54
Yeah sorry I haven't had time to work on resolving NetBox 2.9 issues. I have a presentation I'm working on for a conference so I don't for-see this issue being resolved until late September unless someone wants to step in and try and get updated code to work with 2.9.

**Comment by fdallaca** [comment] 2020-09-08 16:32
Removing prefix obtain another error:
```
{
    "msg": "{\"interface_id\":[\"Select a valid choice. 4 is not one of the available choices.\"]}",
    "changed": false,
    "exception": "  File \"/tmp/ansible_netbox.netbox.netbox_ip_address_payload_9_l1pdiq/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 482, in _nb_endpoint_get\n    response = nb_endpoint.get(**query_params)\n  File \"/opt/custom-venvs/netbox/lib/python3.6/site-packages/pynetbox/core/endpoint.py\", line 138, in get\n    filter_lookup = self.filter(**kwargs)\n  File \"/opt/custom-venvs/netbox/lib/python3.6/site-packages/pynetbox/core/endpoint.py\", line 225, in filter\n    return response_loader(req.get(), self.return_obj, self)\n  File \"/opt/custom-venvs/netbox/lib/python3.6/site-packages/pynetbox/core/query.py\", line 352, in get\n    return req_all()\n  File \"/opt/custom-venvs/netbox/lib/python3.6/site-packages/pynetbox/core/query.py\", line 303, in req_all\n    req = self._make_call(add_params=add_params)\n  File \"/opt/custom-venvs/netbox/lib/python3.6/site-packages/pynetbox/core/query.py\", line 274, in _make_call\n    raise RequestError(req)\n",
    "invocation": {
        "module_args": {
            "netbox_url": "http://ansibledeploy15.private.cineca.it:8000",
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "data": {
                "address": "10.100.8.66/23",
                "interface": {
                    "name": "interface_311_Server-Backend-3",
                    "virtual_machine": "ansibledeploy11.private.cineca.it"
                },
                "family": null,
                "prefix": null,
                "vrf": null,
                "tenant": null,
                "status": null,
                "role": null,
                "description": null,
                "nat_inside": null,
                "dns_name": null,
                "tags": null,
                "custom_fields": null
            },
            "state": "present",
            "validate_certs": true,
            "query_params": null
        }
    },
    "_ansible_no_log": false,
    "item": "10.100.8.66/23",
    "ansible_loop_var": "item",
    "_ansible_item_label": "10.100.8.66/23"
}
```

The only way to create/update ips is using URI module (with POST/PATCH/PUT methods):
(following code for creation)
```
# Create all interface ip
- name: Create ip
  uri:
    url: "{{ netbox_api }}/ipam/ip-addresses/"
    headers:
      Accept: 'application/json'
      Authorization: 'Token {{ netbox_token }}'
    force_basic_auth: yes
    method: "POST"
    body_format: "json"
    body: "{
        'address': '{{ item | ipaddr('address/prefix') }}',
        'status': 'active',
        'assigned_object_id': {{ interface_ensured.interface.id }},
        'assigned_object_type': 'virtualization.vminterface'
      }"
    validate_certs: no
    status_code:
      - 201
  register: response
```

**Comment by FragmentedPacket** [comment] 2020-09-09 01:33
Is the Netbox version reported wrong here? I think the errors are related to changes in Netbox 2.9

**Comment by fdallaca** [comment] 2020-09-09 07:18
Hi @FragmentedPacket ,
Sorry, it's true. Yesterday I proceeded with netbox upgrade (whishing resolve problem) from 2.8.7 to 2.9.3 version. But I also tried without prefixes in 2.8.7 netbox version.
There is somewhere reported a matrix for ansible collection, netbox and pynetbox version requirements? (or a best practice to adopt?)
Thank you in advance for answer.

**Comment by autogun** [comment] 2020-09-24 19:46
Hi @FragmentedPacket,
Encountered the same error after upgrading from 2.8.9 to 2.9.3/4 - `Select a valid choice. 1736 is not one of the available choices.` 

What changes are you referring to? Is this a known issue that need to be addressed on `netbox_ip_address` module level?

**Comment by FragmentedPacket** [comment] 2020-09-24 20:23
The endpoint now uses `assigned_object_id` and `assigned_object_type` in 2.9 rather than just `interface` like it did previously.

The module needs updated to account for that.

**Comment by FragmentedPacket** [comment] 2020-10-02 01:30
@fdallaca I will look into this once I get this collection back up to par with features that were broken due to 2.9 release.

**Comment by FragmentedPacket** [comment] 2020-10-12 01:52
@garbled1 @fdallaca @autogun if you upgrade to the latest collection release, is your issue resolved?

**Comment by autogun** [comment] 2020-10-12 05:25
@FragmentedPacket, yes, issue is resolved. Thank you for the hard work as I've seen this was a tricky one.

**Comment by FragmentedPacket** [comment] 2020-10-12 12:59
Thanks for the kudos! I appreciate the feedback and info that everyone has provided!

**Closed by FragmentedPacket** 2020-10-12 12:59 UTC
Labels: Discussion, Waiting on response, bug
