### ISSUE TITLE
[Feature]: Reset a field to blank

### ISSUE THREAD

**Issue by schmittvictor** [netbox-community/ansible_modules#776] opened 2022-04-21 14:52 UTC
### NetBox version

v3.2.0

### Feature type

Change to existing Module

### Proposed functionality

Unless I'm mistaken there is no way to reset a field.

So it would be usefull that, for example, when setting a field to _None_ it would reset the field to blank.

### Use case

ex: 
```
- netbox.netbox.netbox_device_interface:
    data:
      device: Router
      name: GigabitEthernet0/0/0
      type: "other"
      mtu: None
    state: present
```

result: 
```
{
    "diff": {
        "after": {
            "mtu": null
        },
        "before": {
            "mtu": 1500
        }
    }
}
```

**Comment by sc68cal** [comment] 2022-04-22 17:49
I think the problem is that all the fields that you don't set, end up with a default of `None` - so how do we differentiate between a `None` value that means "I didn't set this field, don't change anything` versus `Delete this value` ?

**Comment by rodvand** [comment] 2022-04-22 18:06
Related discussion https://github.com/netbox-community/ansible_modules/issues/330

**Comment by sc68cal** [comment] 2022-04-26 20:49
I think it would have to be part of a larger overall effort to start using the [network resource module states](https://docs.ansible.com/ansible/latest/network/user_guide/network_resource_modules.html#network-resource-module-states)

**Comment by rodvand** [comment] 2022-11-27 18:29
I'm closing this out as it's a duplicate of https://github.com/netbox-community/ansible_modules/issues/330.

**Closed by rodvand** 2022-11-27 18:29 UTC
Labels: Enhancement
