### ISSUE TITLE
[Bug]: Can't specify master when creating Virtual Chassis

### ISSUE THREAD

**Issue by schmittvictor** [netbox-community/ansible_modules#855] opened 2022-10-26 08:00 UTC
### Ansible NetBox Collection version

v3.8.1

### Ansible version

```bash
ansible [core 2.13.4]
  config file = /home/vsc/ansible/ansible.cfg
  configured module search path = ['/usr/local/lib/python3.6/site-packages/napalm_ansible/modules']
  ansible python module location = /usr/local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/vsc/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.5 (main, Jun 21 2022, 14:56:51) [GCC 8.5.0 20210514 (Red Hat 8.5.0-10)]
  jinja version = 3.1.2
  libyaml = True
```

### NetBox version

v3.5.5

### Python version

3.10

### Steps to Reproduce

```
- netbox.netbox.netbox_virtual_chassis:
    netbox_url: "{{ nb_url }}"
    netbox_token: "{{ nb_token }}"
    validate_certs: false
    data:
      name: SW1
      master: SW1
    state: present
```

Results: 
```
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'                                                                                                                                                        
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1666771134.6456313-2934880-160897441695785 `" && echo ansible-tmp-166677113
4.6456313-2934880-160897441695785="` echo /root/.ansible/tmp/ansible-tmp-1666771134.6456313-2934880-160897441695785 `" ) && sleep 0'                                                                       
Using module file /home/vsc/ansible/collections/ansible_collections/netbox/netbox/plugins/modules/netbox_virtual_chassis.py                                                                                
<localhost> PUT /root/.ansible/tmp/ansible-local-2933158y7ii0jil/tmp1kmzj210 TO /root/.ansible/tmp/ansible-tmp-1666771134.6456313-2934880-160897441695785/AnsiballZ_netbox_virtual_chassis.py              
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1666771134.6456313-2934880-160897441695785/ /root/.ansible/tmp/ansible-tmp-1666771134.6456313-2934880-160897441695785/AnsiballZ_netbox
_virtual_chassis.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/local/bin/python3.10 /root/.ansible/tmp/ansible-tmp-1666771134.6456313-2934880-160897441695785/AnsiballZ_netbox_virtual_chassis.py && sleep 0'                           
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1666771134.6456313-2934880-160897441695785/ > /dev/null 2>&1 && sleep 0'                                                              
The full traceback is:
  File "/tmp/ansible_netbox.netbox.netbox_virtual_chassis_payload_3xt5rzwa/ansible_netbox.netbox.netbox_virtual_chassis_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py",
 line 700, in _nb_endpoint_get
    response = nb_endpoint.get(**query_params)
  File "/usr/local/lib/python3.10/site-packages/pynetbox/core/endpoint.py", line 153, in get
    raise ValueError(
fatal: [SW1 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "cert": null,
            "data": {
                "custom_fields": null,
                "domain": null,
                "master": "SW1",
                "name": "SW1",
                "tags": null
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "https://netbox.com/",
            "query_params": null,
            "state": "present",
            "validate_certs": false
        }
    }
}

MSG:

More than one result returned for master
```

OR

```
- netbox.netbox.netbox_virtual_chassis:
    netbox_url: "{{ nb_url }}"
    netbox_token: "{{ nb_token }}"
    validate_certs: false
    data:
      name: SW1
      master: 5
    state: present
```
Results: 
```
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1667211733.199135-2254020-85805585519981 `" && echo ansible-tmp-1667211733.199135-2254020-85805585519981="` echo /root/.ansible/tmp/ansible-tmp-1667211733.199135-2254020-85805585519981 `" ) && sleep 0'                                                                             
Using module file /home/vsc/ansible/collections/ansible_collections/netbox/netbox/plugins/modules/netbox_virtual_chassis.py                                                                                
<localhost> PUT /root/.ansible/tmp/ansible-local-2253346srxbgbxd/tmpjrgg0r2d TO /root/.ansible/tmp/ansible-tmp-1667211733.199135-2254020-85805585519981/AnsiballZ_netbox_virtual_chassis.py                
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1667211733.199135-2254020-85805585519981/ /root/.ansible/tmp/ansible-tmp-1667211733.199135-2254020-85805585519981/AnsiballZ_netbox_virtual_chassis.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/local/bin/python3.10 /root/.ansible/tmp/ansible-tmp-1667211733.199135-2254020-85805585519981/AnsiballZ_netbox_virtual_chassis.py && sleep 0'                             
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1667211733.199135-2254020-85805585519981/ > /dev/null 2>&1 && sleep 0'                                                                
The full traceback is:
  File "/tmp/ansible_netbox.netbox.netbox_virtual_chassis_payload_6umadfsi/ansible_netbox.netbox.netbox_virtual_chassis_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 700, in _nb_endpoint_get
    response = nb_endpoint.get(**query_params)
  File "/usr/local/lib/python3.10/site-packages/pynetbox/core/endpoint.py", line 153, in get
    raise ValueError(
fatal: [SW1 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "cert": null,
            "data": {
                "custom_fields": null,
                "domain": null,
                "master": 5,
                "name": "SW1",
                "tags": null
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "https://netbox.xx.com/",
            "query_params": null,
            "state": "present",
            "validate_certs": false
        }
    }
}

MSG:

More than one result returned for master
```

I have only one device named `SW1`

Note: I have another device named `SW1 (replaced)` in case it matters...

### Expected Behavior

Create a Virtual Chassis with a master.

**Comment by rodvand** [comment] 2022-10-26 08:25
I'm unable to reproduce this, could you add some debug to your playbook run (-vvv) and post the result?

**Comment by schmittvictor** [comment] 2022-10-26 10:19
> I'm unable to reproduce this, could you add some debug to your playbook run (-vvv) and post the result?

I edited my post

**Comment by rodvand** [comment] 2022-11-27 11:33
I could still not reproduce this issue, for me it works fine.

**Comment by rodvand** [comment] 2023-02-12 15:22
Gonna close this out as I can't reproduce the issue. If you have some more details that can be reproduced we can look at it closer.

**Closed by rodvand** 2023-02-12 15:22 UTC
Labels: bug

**Comment by lasmarois** [comment] 2025-07-10 02:31
## 🔧 **SOLUTION FOUND** - Root Cause and Fix for Virtual Chassis Master Assignment

I just encountered and resolved this exact issue in July 2025. The problem occurs when you have devices with similar names (e.g., `SW1` and `SW1 (replaced)` as mentioned in the original issue).

### **Root Cause**
The issue is in `/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py` in the `QUERY_TYPES` dictionary around line 135. The `master` parameter is **missing** from this dictionary, causing the module to fall back to a general search query (`q=device_name`) instead of an exact name search (`name=device_name`).

When searching for master device `SW1`, the general query matches both:
- `SW1` 
- `SW1 (replaced)`

This triggers the "More than one result returned for master" error in pynetbox.

### **The Fix**
Add the missing entry to the `QUERY_TYPES` dictionary:

```python
QUERY_TYPES = dict(
    asn="asn",
    circuit="cid",
    # ... existing entries ...
    manufacturer="slug",
    master="name",  # <-- ADD THIS LINE
    modules="id",
    # ... rest of existing entries ...
)
```

### **File Location**
`/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py`

### **Why This Works**
- **Before**: `{"q": "SW1"}` - matches any device containing "SW1"
- **After**: `{"name": "SW1"}` - matches only devices with exact name "SW1"

### **Code Flow Analysis**
1. Virtual chassis module calls `_find_ids()` for the `master` parameter
2. `_find_ids()` looks up query type in `QUERY_TYPES.get(k, "q")` 
3. Missing `master` entry defaults to `"q"` (general search)
4. This creates query `{"q": "SW1"}` instead of `{"name": "SW1"}`
5. General search matches multiple devices with similar names
6. pynetbox raises "More than one result returned" ValueError

### **Testing Results**
After applying this fix:
✅ Virtual chassis creation works with similar device names  
✅ Master device assignment works correctly  
✅ No more "More than one result returned" errors  
✅ Tested with devices named `swe1-mtl2-c3` and `swe1-mtl2-c3-stack-unit-2`

### **Versions Tested**
- NetBox Collection: Latest (contains the same code structure)
- NetBox: v3.5+ 
- Ansible: 2.13+
- pynetbox: 7.4.1

This appears to be a long-standing bug in the NetBox Ansible collection that affects any environment with devices having similar names. The fix is minimal, backward-compatible, and follows the existing pattern in the codebase.

**Can this be included in the next release?** This would resolve virtual chassis creation issues for anyone with similar device naming patterns.

### **Related**
This same pattern should be verified for other device reference fields that might have similar issues.
