### ISSUE TITLE
netbox_device_interface error using 'mode'.

### ISSUE THREAD

**Issue by ThomasADavis** [netbox-community/ansible_modules#158] opened 2020-04-04 18:05 UTC
##### ISSUE TYPE
 - Bug Report

###### Ansible:
[tdavis@mouse-r11 netbox]$ ansible --version
ansible 2.9.6
  config file = /home/tdavis/netbox/ansible.cfg
  configured module search path = ['/home/tdavis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tdavis/.local/lib/python3.6/site-packages/ansible
  executable location = /home/tdavis/.local/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
###### Netbox:

v2.7.11

###### Collection:

github  head installed.
##### SUMMARY

Tagged All vs. Tagged (All)

##### STEPS TO REPRODUCE
```
    - name: create real interfaces
      netbox_device_interface:
        netbox_url: "{{ endpoint }}"
        netbox_token: "{{ token }}"
        data:
          device: "{{ ansible_hostname }}"
          name: "{{ item.name }}"
          form_factor: "{{ item.form_factor }}"
          tags: "{{ item.tags }}"
          mode: "Tagged All"
          mtu: "{{ item.mtu | default(1514) }}"
      loop: "{{ interfaces }}"

```

##### EXPECTED RESULTS

succeded.

##### ACTUAL RESULTS

```
failed: [mouse-r12] (item={'name': 'enp2s0', 'form_factor': '1000BASE-T (1GE)', 'tags': ['ovsbridge:br-external'], 'mtu': 9216}) => {"ansible_loop_var": "item", "changed": false, "item": {"form_factor": "1000BASE-T (1GE)", "mtu": 9216, "name": "enp2s0", "tags": ["ovsbridge:br-external"]}, "msg": "Tagged All was not found as a valid choice for interfaces"}
```

Looking at the _choices API, it should be 'Tagged (All)', not 'Tagged All'.  This affects netbox_vm_interface, netbox_device_interface, and netbox_interface.

**Comment by FragmentedPacket** [comment] 2020-04-05 14:40
@ThomasADavis I'm sorry, but what is the exact issue here? The choices are fetched dynamically for the two modules that we're support (`netbox_device_interface` and `netbox_vm_interface`) from the NetBox API so the user will have to pass in the correct mode that would be valid for NetBox.

Is this a documentation issue? Sorry just not very clear as to where the issue is.

**Comment by ThomasADavis** [comment] 2020-04-05 19:12
They are not dynamic. 

```
def main():
    """
    Main entry point for module execution
    """
    argument_spec = NETBOX_ARG_SPEC
    argument_spec.update(
        dict(
            update_vc_child=dict(type="bool", required=False, default=False),
            data=dict(
                type="dict",
                required=True,
                options=dict(
                    device=dict(required=False, type="raw"),
                    name=dict(required=True, type="str"),
                    form_factor=dict(required=False, type="raw"),
                    enabled=dict(required=False, type="bool"),
                    lag=dict(required=False, type="raw"),
                    mtu=dict(required=False, type="int"),
                    mac_address=dict(required=False, type="str"),
                    mgmt_only=dict(required=False, type="bool"),
                    description=dict(required=False, type="str"),
                    mode=dict(
                        required=False, choices=["Access", "Tagged", "Tagged All"],
                    ),
                    untagged_vlan=dict(required=False, type="raw"),
                    tagged_vlans=dict(required=False, type="raw"),
                    tags=dict(required=False, type="list"),
                ),
            ),
        )
    )
```

Hard coded values in the modules.

When using netbox 2.7, that should be 'Tagged (All)', not 'Tagged All'

All three modules have the same hard coded values.

**Comment by FragmentedPacket** [comment] 2020-04-05 19:17
Great. Thank you for the specifics. I can get something put in tonight hopefully.

**Comment by ThomasADavis** [comment] 2020-04-05 19:18
Looks like it should just be commented out, not changed - netbox-2.8 is the flag day version for slugs.

**Comment by FragmentedPacket** [comment] 2020-04-05 19:53
Did you mean to close this issue? And we can make a decision as to whether it should be commented out or not.

I'd rather have a few choices (slug and not slug) that it will validate whether they provided the correct options, but having the API report back that it is an invalid option is also fine and prevents having the argument spec, but goes through all the logic, etc. before failing.

**Comment by ThomasADavis** [comment] 2020-04-05 19:54
Dang it.  Hit the wrongbutton.

**Comment by ThomasADavis** [comment] 2020-04-05 19:55
I looked in other modules, the same code section was commented out, and appears to handled somewhere else.

and it only affects netbox_vm_interface and netbox_device_interface.  netbox_interfaces does no checking.

**Comment by FragmentedPacket** [comment] 2020-04-05 19:58
Yeah the argument spec is newer. I think changing the type to raw and then I'll look at the back end code since I think those are available from the _choices API endpoint

**Comment by ThomasADavis** [comment] 2020-04-06 22:01
Looks good to me.

**Closed** 2020-04-06 23:25 UTC
Labels: PR Submitted, bug
