### ISSUE TITLE
[Bug]: Upgrade from v3.6.0 to v3.7.0 breaks connection to Netbox

### ISSUE THREAD

**Issue by m-kratochvil** [netbox-community/ansible_modules#774] opened 2022-04-20 16:11 UTC
### Ansible NetBox Collection version

v3.7.0

### Ansible version

```bash
ansible [core 2.12.2]
  config file = /home/ccloud/ccloud-net/ansible.cfg
  configured module search path = ['/home/ccloud/ccloud-net/plugins/modules']
  ansible python module location = /home/ccloud/.venv/core212/lib/python3.8/site-packages/ansible
  ansible collection location = /home/ccloud/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ccloud/.venv/core212/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.0.3
  libyaml = True
```

### NetBox version

v2.9.3

### Python version

3.8

### Steps to Reproduce

Simple fetch of data from Netbox fails in the `nb_inventory.py` script, at the `open_url(` function.
Sorry if I'm not describing it properly, I'm not a developer.

### Expected Behavior

Data from Netbox should be fetched.

### Observed Behavior

Following exception was raised:

```Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/ccloud/.ansible/collections/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 354, in _fetch_information
    response = open_url(
  File "/home/ccloud/.venv/core212/lib/python3.8/site-packages/ansible/module_utils/urls.py", line 1535, in open_url
    return Request().open(method, url, data=data, headers=headers, use_proxy=use_proxy,
  File "/home/ccloud/.venv/core212/lib/python3.8/site-packages/ansible/module_utils/urls.py", line 1446, in open
    return urllib_request.urlopen(request, None, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ccloud/.ansible/collections/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 1345, in wrapper
    raise e
  File "/home/ccloud/.ansible/collections/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 1340, in wrapper
    lookup()
  File "/home/ccloud/.ansible/collections/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 983, in refresh_site_groups_lookup
    site_groups = self.get_resource_list(api_url=url)
  File "/home/ccloud/.ansible/collections/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 412, in get_resource_list
    api_output = self._fetch_information(api_url)
  File "/home/ccloud/.ansible/collections/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 380, in _fetch_information
    raise AnsibleError(to_native(e.fp.read()))
ansible.errors.AnsibleError:

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Page Not Found - NetBox</title>
```
Followed by a massive output of html code..

**Comment by rodvand** [comment] 2022-04-20 18:11
Hi! Could you show the inventory file you are using so that we can attempt to replicate? And, I'm sure you're aware, but NetBox 2.9 is very old so you should look into upgrading.

**Comment by m-kratochvil** [comment] 2022-04-21 05:43
Hi @rodvand ,
thanks a lot for looking into this.

There's no inventory file involved at the point of the failure. For ansible playbooks, we use static inventory files in .yaml format and those work well, but to build those inventory files, we fetch data from Netbox, using the `netbox.netbox.nb_inventory` module from this collection, in a Python script.
To reproduce the issue on your side, if you run the above module against a localhost, with `api_endpoint` being a Netbox v2.9.3 it will fail. The Netbox version being an issue here is my assumption, I have unfortunately no way to check against other Netbox versions..

An example of our config file for the `netbox.netbox.nb_inventory` module:
```
plugin: netbox.netbox.nb_inventory
api_endpoint: https://netbox.global.cloud
validate_certs: no
services: False
query_filters:
  - status: active
group_by:
  - sites
  - region
```

**Comment by ryanmerolle** [comment] 2022-04-25 21:42
3.7.1 will have a fix for `nb_inventory` introduced in 3.7.0, but I am doubtful this is your issue since it only impacts users when you select `group_by: ["site_group"]`, but I could be missing another trigger to reproduce it.  `nb_inventory` was only touched in 3.7.0 to add the new site_group functionality.

We generally only test new releases with the last 3 major releases (3.2, 3.1, 3.0), but because the last version of 2.11 was released less than a  year ago, we decided to include it for now.

A lot of the feature the updates for netbox collection mostly focus on adding features introduced by NetBox in recent versions.

IE if you are looking to freeze your NetBox install to a release from a little over 1.5 years ago, you may want to ping your netbox ansible collection as new versions really won't focus on those versions.

For right now you have 2 options:

- See if netbox.netbox 3.7.1 fixes your issue when it is released in the next day or so
- Pin to netbox.netbox 3.6.0 collection version
- Test netbox.netbox 3.7.1 with an updated version of NetBox 2.11 or newer

**Comment by m-kratochvil** [comment] 2022-04-26 06:01
@ryanmerolle Thanks for the explanation, and the fix, much appreciated. I realize the Netbox version we use often causes issues, and we're definitely not locked to it, working on an upgrade plan.
I will test the fix in 3.7.1 once out and give a feedback here.

**Comment by ryanmerolle** [comment] 2022-04-27 01:23
I think the merge autoclosed this.  I will reopen until @m-kratochvil confirms

**Comment by rodvand** [comment] 2022-04-27 20:01
I reproduced the issue on a 2.9 version and tested afterwards, so I'll close this. If anything else, feel free to open a new issue @m-kratochvil

**Closed by rodvand** 2022-04-27 20:01 UTC
Labels: bug

**Comment by m-kratochvil** [comment] 2022-04-28 18:09
I confirm v3.7.1 fixes the issue. Thanks again @rodvand and @ryanmerolle for your assistance, much appreciated!
