### ISSUE TITLE
how to modify an specific attribute to None 

### ISSUE THREAD

**Issue by dsz211** [netbox-community/ansible_modules#347] opened 2020-09-30 07:20 UTC
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Module question
##### SUMMARY

for example, vlan_119 belong to site: xyz, role:abc, tenant: 123
we want to remove vlan_119's attribute(site/role/tenant).
```
- name: modify vlan"
  collections:
    - netbox.netbox
  netbox_vlan:
    netbox_url: "{{ _netbox_url }}"
    netbox_token: "{{ _netbox_token }}"
    state: "present"
    validate_certs: no
    data:
      name: "vlan_119"
      vid: "11"
      site: 
      tenant: 
      vlan_role: 
    query_params:
      - vid
      - group
      - site
```
but it did not change anyting of the role/site/tennat
 ##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

 remove vlan_119's attribute(site/role/tenant).
##### ACTUAL RESULTS

nothing changed

```

```

**Comment by FragmentedPacket** [comment] 2020-10-02 01:34
I need to look into the best method for this. I believe I have an idea and will hopefully get time to implement it in the next few weeks.

**Comment by FragmentedPacket** [comment] 2020-10-12 01:49
I believe this is a duplicate of #330. This collection needs to ability for the user to set fields on the object to None.

I will start working on this tonight but I believe it will be a pretty big change and may take some time to implement.

**Closed by FragmentedPacket** 2020-10-12 01:49 UTC
Labels: Enhancement, PR Required, help wanted
